@host_api = http://localhost:5000
@api_prefix = http_coap

GET {{host_api}}/status


### GET BUTTON STATE

PUT {{host_api}}/{{api_prefix}}/interface
content-type: application/json

{
    "coap_server_ip" : "192.168.0.103",
    "coap_server_port" : 5683,
    "coap_server_resource" : "button",
    "coap_method" : "get"
}


### GET LIGHT STATE

PUT {{host_api}}/{{api_prefix}}/interface
content-type: application/json

{
    "coap_server_ip" : "192.168.0.103",
    "coap_server_port" : 5683,
    "coap_server_resource" : "light",
    "coap_method" : "get"
}


### SET LIGHT STATE

PUT {{host_api}}/{{api_prefix}}/interface
content-type: application/json

{
    "coap_server_ip" : "192.168.0.103",
    "coap_server_port" : 5683,
    "coap_server_resource" : "light",
    "coap_method" : "put",
    "coap_payload" : {
        "light": true
    }
}


### SEND INVALID COAP REQUEST

PUT {{host_api}}/{{api_prefix}}/interface/
content-type: application/json

{
    "key": "value"
}

### SEND INVALID REQUEST (WITHOUT REQUEST BODY)

PUT {{host_api}}/{{api_prefix}}/interface/


### SEND BAD REQUEST OVER LIGHT RESOURCE

PUT {{host_api}}/{{api_prefix}}/interface/
content-type: application/json

{
    "coap_server_ip" : "192.168.0.103",
    "coap_server_port" : 5683,
    "coap_server_resource" : "light",
    "coap_method" : "put",
    "coap_payload" : "Bad Request Payload"
}


### SEND NOT ALLOWED (POST) REQUEST OVER LIGHT RESOURCE

PUT {{host_api}}/{{api_prefix}}/interface/
content-type: application/json

{
    "coap_server_ip" : "192.168.0.103",
    "coap_server_port" : 5683,
    "coap_server_resource" : "light",
    "coap_method" : "post",
    "coap_payload" : {
        "light": false
    }
}


### SEND NOT ALLOWED (DELETE) REQUEST OVER LIGHT RESOURCE

PUT {{host_api}}/{{api_prefix}}/interface/
content-type: application/json

{
    "coap_server_ip" : "192.168.0.103",
    "coap_server_port" : 5683,
    "coap_server_resource" : "light",
    "coap_method" : "delete",
    "coap_payload" : {
        "light": false
    }
}